export const SWITCH_MENU = "SWITCH_MENU";
export const SET_DOTS = "SET_DOTS";
export const SET_LANG = "SET_LANG";

export const SEND_NOTIFICATION = "SEND_NOTIFICATION";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const USER_LOGIN_SUCCES = "USER_LOGIN_SUCCES";
